/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project.euler;
import java.math.BigInteger;
/**
 *
 * @author wenwenxu
 */

/*
 * Even Fibonacci numbers
 * Problem 2 
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
 * By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
 * find the sum of the even-valued terms.
*/
public class P2 {

	public static void Fibonacci(int number)
	{

		for(int i = 1; i < number ; i++)
		{
			
		}
	}
	

	public static void main(String[] args) {
		
		
	
	}

}